### ISSUE TITLE
GUI won't load

### ISSUE THREAD

**Issue by choomaque** [brummer10/ToneTwistPlugs#2] opened 2023-10-04 19:32 UTC
Windows 11 Pro 22621.2283, FL Studio 21 (v21.1.1), VST3 versions GUI won't load/render showing just blank black space instead inside of a plugin window.

![image](https://github.com/brummer10/ToneTwistPlugs/assets/39616153/14ff2f2c-df39-4e9b-b52b-c0c7943aaf6d)

UPD: 
Dragging the plugin window on VST3 versions reveals GUI, but only part of it, and the GUI scales when dragging the corner of a plugin window. 

VST2 versions have the identical issue with the GUI.

**Comment by KlashKontakt** [comment] 2023-10-05 06:43
Helo! 
I confirm problem with gui on Renoise 3.4.3 osx 13.6 i can't find vst3 version after scanning and gui don't work


<img width="326" alt="Снимок экрана 2023-10-05 в 08 40 55" src="https://github.com/brummer10/ToneTwistPlugs/assets/87890552/e851680a-f993-4dbb-b7b4-122eef875b9c">

**Comment by brummer10** [comment] 2023-10-05 07:48
Hi
Thanks for reporting the issue.


> Windows 11 Pro 22621.2283, FL Studio 21 (v21.1.1), VST3 versions GUI won't load/render showing just blank black space instead inside of a plugin window.

I did a quick check on windows and indeed, there is a issue. It seems the GUI has a offset which moves it out of the visible area. When you enlarge the plug window it becomes visible. 
That's a bug. I hope it could be fixed soon.


> I confirm problem with gui on Renoise 3.4.3 osx 13.6 i can't find vst3 version after scanning and gui don't work

So what is it there, it is the vst2 version or the stand-alone? May it be the same issue as above, I mean becomes the GUI visible when you enlarge the UI?

**Comment by KlashKontakt** [comment] 2023-10-05 09:26
nope! I can't resizing window 
<img width="875" alt="Снимок экрана 2023-10-05 в 11 26 26" src="https://github.com/brummer10/ToneTwistPlugs/assets/87890552/cd284bd2-ed4d-484d-86d8-4b28805e090f">

**Comment by brummer10** [comment] 2023-10-05 15:14
A new release is out, the issues you've reported should be fixed now. 
One exception may be Renoise, I've checked it in Renoise and see that Renoise only enable 1 vst3 plug from ToneTwistPlugs, and hide all the others. Only vst2 plugs will be shown as expected.
https://github.com/brummer10/ToneTwistPlugs/releases/tag/v0.5

**Comment by choomaque** [comment] 2023-10-05 16:02
Tested v0.5 VST3, everything works so far. Thanks for reacting this swift.

**Comment by armand1m** [comment] 2023-10-06 11:33
<img width="285" alt="Screenshot 2023-10-06 at 13 31 21" src="https://github.com/brummer10/ToneTwistPlugs/assets/6154901/5c45f1d4-a3ca-4d6c-961d-cea00b460cc3">

I have the same issue happening on Mac M1, happens both with VST3 and VST2, also when using the app.

I've installed the mac universal dmg: https://github.com/brummer10/ToneTwistPlugs/releases/download/v0.5/ToneTwistPlugs-v0.5-macos-universal.dmg

**Comment by brummer10** [comment] 2023-10-06 13:37
Hi
To bad. So the macos interface is still broken. 
When you enlarge the GUI, do you see anything then? I guess some high-dpi stuff is broken in the macos wrapper. 
Do you use a high-dpi display with scaling?
Also, do you get the same issue with the v0.4 release?

**Comment by armand1m** [comment] 2023-10-06 14:22
I cannot enlarge the UI :/ also didn't try the v0.4 yet, let me give it a try in a minute

**Comment by brummer10** [comment] 2023-10-07 12:52
A new release is out, I hope the issue is now finally fixed.

https://github.com/brummer10/ToneTwistPlugs/releases/tag/v0.6

**Comment by brummer10** [comment] 2023-10-09 16:40
@armand1m  @KlashKontakt 
when you've still the issue with the latest v0.6 version, feel free to open a new issue. 
This one will be closed now.

**Closed as completed by brummer10** 2023-10-09 16:40 UTC
Labels: bug

**Comment by RustoMCSpit** [comment] 2024-05-20 01:25
GUI doesnt load still on Biwig 5.8
clap 
linux mint lts

**Comment by brummer10** [comment] 2024-05-20 05:43
Could you try if StompTuner works for you? 
https://github.com/brummer10/StompTuner
If so, I may just need to update DPF.

**Comment by RustoMCSpit** [comment] 2024-05-20 16:51
> Could you try if StompTuner works for you? https://github.com/brummer10/StompTuner If so, I may just need to update DPF.

nope doesnt work

**Comment by brummer10** [comment] 2024-05-20 16:55
Strange is, that I've reports that it works flawless in Bitwig
https://github.com/brummer10/StompTuner/issues/3

Do you use Wayland? Flatpack?

**Comment by RustoMCSpit** [comment] 2024-05-20 16:55
i use bitwig as a .deb on x server, not wayland

**Comment by RustoMCSpit** [comment] 2024-05-20 16:56
any way i can run a log report on it and paste it here?

**Comment by brummer10** [comment] 2024-05-20 17:06
That's not easy. Remember that a plug runs as part of the host, loaded as library. So it is required that the host provide the debugging info. 
Have you the same issue in Ardour, Carla, Qtractor, Reaper, Reason, . . . or is it specific to bitwig.
Do you use the provided binary, or do you build the plugs yourself?

**Comment by RustoMCSpit** [comment] 2024-05-20 17:11
i use the provided binary.
besides reaper, none of those use clap
how do i make the host provide that info

**Comment by brummer10** [comment] 2024-05-20 18:06
Maybe you are now able to build yourself and they work?

**Comment by RustoMCSpit** [comment] 2024-05-20 18:16
> Maybe you are now able to build yourself and they work?

yeah it works now
